---
# tasks file for deploy_nginx_web

- name: Install nginx for Ubuntu
  apt: name=nginx state=latest

- name: ansible create directory with mode setting example
  file:
    path: /var/www/russnya
    state: directory
    mode: "655"
 
- name: Copy HomePage file to Web Server
  copy: src=index.html dest={{ destin_file_first }}

- name: Copy HomePage file to Web Server
  copy: src=index2.html dest={{ destin_file_second }}

- name: Start Web Server service for Ubuntu
  service: name=nginx state=started enabled=yes
