# ---
# - name: Change nginx to Ubuntu
#   hosts: linux1
#   become: yes

#   vars:
#     nginx_sites: /etc/nginx/sites-available/
#     conf_file: ./default.conf
#    # nginx_sites2: ./

#   tasks:
#     - name: Delete default nginx vhost
#       file:
#         path={{ nginx_sites }}/default
#         state=absent

#     - name: Delete default nginx vhost symlink
#       file: path=/etc/nginx/sites-available/default state=absent
      
#     - name: Copy wit my Ubuntu server nginx vhost
#      # template:
#       copy: src={{ conf_file }} dest={{ nginx_sites }}
#       notify: restart nginx
      
#     - name: Delete default nginx vhost symlink
#       file: path=/etc/nginx/sites-enabled/default state=absent

#     - name: Create symlink nginx vhost
#       file:
#         src={{ nginx_sites }}/{{ conf_file }}
#         dest=/etc/nginx/sites-enabled/{{ conf_file }}
#         state=link
#       notify: restart nginx

#     - name: sleep for 300 seconds and continue with play
#       wait_for: 
#         timeout: 300

#    # - name: Loop Sleep for 60 seconds and continue with play
#    #   delay: 60
#   #    retries: 2
#    #   until: Create symlink nginx vhost

#   # handlers:
#   #   - name: restart nginx
#   #     service: name=nginx state=restarted